clean: true

theme: fullwidth

output: docs
readme: README.md

module: Inotify
swift_build_tool: spm
undocumented_text: ""
github_url: https://github.com/sersoft-gmbh/swift-inotify

author: ser.soft GmbH
author_url: https://sersoft.de
